from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
urlpatterns = [
    path('', views.home_redirect, name='home'),
    path('clientes/', views.lista_clientes, name='clientes'),
    path('clientes/form/', views.form_cliente, name='form_cliente'),
    path('clientes/<int:pk>/editar/', views.editar_cliente, name='editar_cliente'),
    path('clientes/<int:pk>/eliminar/', views.eliminar_cliente, name='eliminar_cliente'),
    path('ajax/ciudades/', views.obtener_ciudades, name='ajax_ciudades'),
    path('usuarios/', views.lista_usuarios, name='lista_usuarios'),
    path('usuarios/form/', views.form_usuario, name='form_usuario'),
    path('usuarios/eliminar/<int:pk>/', views.eliminar_usuario, name='eliminar_usuario'),
    path('usuarios/toggle-estado/<int:pk>/', views.toggle_estado_usuario, name='toggle_estado_usuario'),
    path('usuarios/obtener-datos-modal-usuario/', views.obtener_datos_modal_usuario, name='obtener_datos_modal_usuario'),
    path('certificados/', views.crear_certificado, name='crear_certificado'),
    path('certificados/<int:pk>/pdf/', views.certificado_pdf, name='certificado_pdf'),
    path('certificados/<int:pk>/factura/', views.factura_pdf, name='factura_pdf'),
    path('certificados/<int:pk>/factura/confirmacion/', views.factura_confirmacion, name='factura_confirmacion'),
    path('cobranzas/', views.vista_cobranzas, name='vista_cobranzas'),
    path('cobranzas/pdf/<int:certificado_id>/', views.generar_pdf_cobranza, name='generar_pdf_cobranza'),
    path('login/', views.login_view, name='login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('api/paises/', views.obtener_paises, name='api_paises'),
    path('api/ciudades/', views.obtener_ciudades, name='api_ciudades'),
    path('api/aeropuertos/', views.obtener_aeropuertos, name='api_aeropuertos'),
    path('api/unlocode/', views.obtener_unlocode, name='api_unlocode'),
    path("logs-actividad/", views.obtener_logs_actividad, name="logs_actividad"),
    path('certificados/probar-envio/', views.probar_envio_factura, name='probar_envio_factura'),
    path('certificados/probar-envio-xml/', views.probar_envio, name='probar_envio'),
    path('api/buscar-aeronaves/', views.buscar_aeronaves, name='buscar_aeronaves'),
    path('api/buscar-navios/', views.buscar_navios, name='buscar_navios'),

]
